# Default settings
title: Luxury Wedding & Event Stylist - Angelic Signature
email: 'info@angelicsignature.com'
description: "A&amp;A Party Poppers is a team of events and wedding venue decorations specialists based in London UK. We offer a wide range of services including: chair and table covers, centrepieces, backdrops, balloon decorations, costumes, kids' entertainment and much more."
